=== kouo00/4iz238-xml/schema.xsd
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.semestralkaMS.cz/LS2018" targetNamespace="http://www.semestralkaMS.cz/LS2018" xmlns:mstns="http://www.semestralkaMS.cz/LS2018" elementFormDefault="qualified" attributeFormDefault="unqualified"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1"
    >
    
    <xs:element name="dodacíList" type="dodacíListType">    
    </xs:element>
    
    <xs:complexType name="DodavatelType">
        <xs:sequence>
            <xs:element type="StringNeniNull" name="Nazev"/>
            <xs:element type="StringNeniNull" name="Mesto"/>
            <xs:element type="StringNeniNull" name="Ulice"/>
            <xs:element type="PSCType" name="PSC"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="ZakaznikType">
        <xs:sequence>
            <xs:element type="StringNeniNull" name="Nazev"/>
            <xs:element type="StringNeniNull" name="Mesto"/>
            <xs:element type="StringNeniNull" name="Ulice"/>
            <xs:element type="PSCType" name="PSC">
            </xs:element>
        </xs:sequence>
        <xs:attribute type="ZakAtrbType" name="typ"/>
    </xs:complexType>
    
    <xs:complexType name="metadataType">
        <xs:sequence>
            <xs:element type="DodListType" name="DodaciList"/>
            <xs:element type="CisObjType" name="CisObj"/>
            <xs:element type="xs:date" name="DatumObjednání"/>
            <xs:element type="xs:date" name="DatumDodání"/>
            <xs:element type="ObjZakType" name="ObjZak"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="HeaderType">
        <xs:sequence>
            <xs:element type="DodavatelType" name="Dodavatel"/>
            <xs:element type="ZakaznikType" name="Zakaznik" minOccurs="2" maxOccurs="2">              
            </xs:element>
        </xs:sequence>
    </xs:complexType>    
    
    <xs:complexType name="PoložkaType">
        <xs:sequence>
            <xs:element type="IdentifikačníČísloType" name="IdentifikačníČíslo"/>
            <xs:element type="StringNeniNull" name="Popis"/>
            <xs:element type="BarvaType" name="Barva"/>
            <xs:element type="StringNeniNull" name="Materiál"/>
            <xs:element type="PohlavíType" name="Pohlaví"/>
            <xs:element type="VelikostType" name="Velikost"/>
            <xs:element type="CenaZaKusType" name="CenaZaKus"/>
            <xs:element type="MnozstviType" name="Mnozstvi"/>
            <xs:element type="ZnačkaType" name="Značka"/>
            <xs:element type="xs:anyURI" name="FotoURI"/>
            <xs:element type="StringNeniNull" name="TXT"/>
        </xs:sequence>
    </xs:complexType>
      
      <xs:simpleType name="PohlavíType">
          <xs:restriction base="xs:string">
              <xs:enumeration value="pánské"/>
              <xs:enumeration value="dámské"/>
              <xs:enumeration value="univerzální"/>
          </xs:restriction>
      </xs:simpleType>
    
    <xs:simpleType name="VelikostType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="37"/>
            <xs:enumeration value="38"/>
            <xs:enumeration value="39"/>
            <xs:enumeration value="40"/>
            <xs:enumeration value="41"/>
            <xs:enumeration value="42"/>
            <xs:enumeration value="43"/>
            <xs:enumeration value="44"/>
            <xs:enumeration value="45"/>
            <xs:enumeration value="XS"/>
            <xs:enumeration value="XS"/>
            <xs:enumeration value="S"/>
            <xs:enumeration value="M"/>
            <xs:enumeration value="L"/>
            <xs:enumeration value="XL"/>
            <xs:enumeration value="uviverzální"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ZnačkaType">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="CenaZaKusType">
            <xs:simpleContent>
                <xs:extension base="xs:float">
                    <xs:attribute name="měna" type="měnaTyp" use="required"/>
                </xs:extension>
            </xs:simpleContent>   
    </xs:complexType>
    
    <xs:simpleType name="měnaTyp">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CZK"/>
            <xs:enumeration value="EUR"/>
            <xs:enumeration value="GBP"/>
            <xs:enumeration value="USD"/>
            <xs:enumeration value="JPY"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="MnozstviType">
        <xs:simpleContent>
            <xs:extension base="xs:float">
                <xs:attribute name="jednotky" type="jednotkyType" use="required"/>
            </xs:extension>
        </xs:simpleContent>   
    </xs:complexType>
    
    <xs:simpleType name="jednotkyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="kusy"/>
            <xs:enumeration value="gramy"/>
            <xs:enumeration value="metry"/>
            <xs:enumeration value="litry"/>
        </xs:restriction>
    </xs:simpleType>
      
    <xs:simpleType name="IdentifikačníČísloType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{10}\D*\p{Lu}{5}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="PoložkyType">
        <xs:sequence>
            <xs:element type="PoložkaType" name="Položka" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="dodacíListType">
        <xs:sequence>
            <xs:element type="metadataType" name="metadata"/>
            <xs:element type="HeaderType" name="Header">
                <xs:unique name="zakaznikKontrola">
                    <xs:selector xpath="mstns:Zakaznik"/>
                    <xs:field xpath="@typ"/>
                </xs:unique> 
            </xs:element>
            <xs:element type="PoložkyType" name="Položky"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="PSCType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[1-9]\d{2}[ ][0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="DodListType">
        <xs:restriction base="xs:string">
            <xs:pattern value="DL\d{6}"/>
        </xs:restriction> 
    </xs:simpleType>
    
    <xs:simpleType name="CisObjType">
        <xs:restriction base="xs:int">
            <xs:pattern value="\d{10}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ObjZakType">
        <xs:restriction base="xs:int">
            <xs:pattern value="\d{10}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ZakAtrbType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="dodací"/>
            <xs:enumeration value="fakturační"/>
        </xs:restriction> 
    </xs:simpleType> 
    
    <xs:simpleType name="StringNeniNull">
        <xs:restriction base="xs:string">
            <xs:minLength value="4"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="BarvaType">
        <xs:restriction base="xs:string">
            <xs:minLength value="3"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== kouo00/4iz238-xml/katalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="schematron.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/xsl" href="html.xsl"?>

<dodacíList xmlns="http://www.horolezci.cz/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.semestralkaMS.cz/LS2018 schema.xsd">
    <metadata>
        <cisloListu>DL220325</cisloListu>
        <CisObj>0000118549</CisObj>
        <DatumObjednání>2016-12-01</DatumObjednání>
        <DatumDodání>2016-12-05</DatumDodání>
        <ObjZak>1519029618</ObjZak>
    </metadata>
    <Header>
        <Dodavatel>
            <Nazev>Animalco a.s.</Nazev>
            <Mesto>Praha 6</Mesto>
            <Ulice>Na Kocínce 1</Ulice>
            <PSC>160 41</PSC>
        </Dodavatel>
        <Zakaznik typ="dodací">
            <Nazev>PMU CZ, a.s.</Nazev>
            <Mesto>Roudnice nad Labem</Mesto>
            <Ulice>Chelčického 627</Ulice>
            <PSC>413 01</PSC>
        </Zakaznik>
        <Zakaznik typ="fakturační">
            <Nazev>PMU CZ, a.s.</Nazev>
            <Mesto>Roudnice nad Labem</Mesto>
            <Ulice>Chelčického 627</Ulice>
            <PSC>413 01</PSC>
        </Zakaznik>
    </Header>
    <Položky>
        <Položka>
            <IdentifikačníČíslo>0203222313BEDBE</IdentifikačníČíslo>
            <Popis>Zimní bunda</Popis>
            <Barva>žlutá</Barva>
            <Materiál>polyester</Materiál>
            <Pohlaví>dámské</Pohlaví>
            <Velikost>S</Velikost>
            <CenaZaKus měna="CZK">1500</CenaZaKus>
            <Mnozstvi jednotky="kusy">15</Mnozstvi>
            <Značka>Mammut</Značka>
            <FotoURI>i1.png</FotoURI>
            <TXT>Lehká nepromokavá bunda do nepříznivého počasí od firmy Mammut, která je vhodná pro širokou škálu outdoorových aktivit. Díky systému Mammut Easy combine lze do bundy vepnout libovolnou izolační vrstvu (fleecka, zateplená bunda) značky Mammut. Vpínací systém je na krku a rukávech, pomocí patentu. Nechybí ani tvarované rukávy, nastavitelná tříbodová kapuce nebo regulace spodního lemu na obou stranách.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>0203222101NEKSP</IdentifikačníČíslo>
            <Popis>Péřovka</Popis>
            <Barva>černá</Barva>
            <Materiál>Polyester</Materiál>
            <Pohlaví>pánské</Pohlaví>
            <Velikost>L</Velikost>
            <CenaZaKus měna="CZK">5400</CenaZaKus>
            <Mnozstvi jednotky="kusy">10</Mnozstvi>
            <Značka>Sir Joseph</Značka>
            <FotoURI>i2.png</FotoURI>
            <TXT>Ultra lehká péřová bunda značky Sir Joseph z řady Light, kterou využijete na jaře, podzim i v zimě. Měla by s vámi být při každé akci v horách a nezklame ani na běžné nošení. Jako záložní izolační vrstva místo fleecky nezabere téměř žádné místo, a navíc ji můžete sbalit do kompresního sáčku, který je součástí bundy.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>0203222789PTRFG</IdentifikačníČíslo>
            <Popis>Kalhoty</Popis>
            <Barva>Hnědá</Barva>
            <Materiál>64% Bavlna, 36% Nylon</Materiál>
            <Pohlaví>pánské</Pohlaví>
            <Velikost>XL</Velikost>
            <CenaZaKus měna="CZK">2000</CenaZaKus>
            <Mnozstvi jednotky="kusy">13</Mnozstvi>
            <Značka>Arc teryx</Značka>
            <FotoURI>i3.png</FotoURI>
            <TXT>Velice všestranné kalhoty od firmy Arc teryx z odolného materiálu, které se hodí jak do města, tak na outdoorové výlety. Jejich konstrukce poskytuje svobodu pohybu a nabízí skvělý design, který rozhodně nezklame ani ve společnosti.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>0349876521USPCK</IdentifikačníČíslo>
            <Popis>Kalhoty</Popis>
            <Barva>Oranžová</Barva>
            <Materiál>Eco-shell</Materiál>
            <Pohlaví>pánské</Pohlaví>
            <Velikost>M</Velikost>
            <CenaZaKus měna="CZK">12000</CenaZaKus>
            <Mnozstvi jednotky="kusy">5</Mnozstvi>
            <Značka>Fjällräven</Značka>
            <FotoURI>i4.png</FotoURI>
            <TXT>Pánské nepromokavé kalhoty z materiálu Eco-shell od firmy Fjällräven pro aktivní pohyb v horském terénu. Na skialpy, sněžnice nebo několikadenní přechody...nic pro ně není problém. Jejich snadné obléknutí nebo svléknutí přes obuv umožní rozepínatelné nohavice po celé délce. Kalhoty pro zvýšení odolnosti jsou zesílené materiálem Corylon v oblasti kolen, pasu a vnitřní strany nohavic ve spodní části.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>0369403158XNVKP</IdentifikačníČíslo>
            <Popis>Lezečky</Popis>
            <Barva>Žlutá, černá</Barva>
            <Materiál>Keprová tkanina, guma</Materiál>
            <Pohlaví>pánské</Pohlaví>
            <Velikost>44</Velikost>
            <CenaZaKus měna="CZK">1100</CenaZaKus>
            <Mnozstvi jednotky="kusy">6</Mnozstvi>
            <Značka>OCUN</Značka>
            <FotoURI>i5.png</FotoURI>
            <TXT>Velmi komfortní lezečky v klasickém šněrovacím provedení od firmy OCUN, které jsou primárně určené pro začínající lezce. Firma především kladla důraz na kvalitní ogumování včetně špičky. Díky plochému a jen velmi mírně asymetrickému kopytu nabízí tato bota komfort širokému spektru typů chodidel. Především začátečníci ocení ekonomický model Crest LU, ve kterém si budou své první stovky metrů lezení pohodlně užívat.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>4672168951PLOIU</IdentifikačníČíslo>
            <Popis>Lezečky</Popis>
            <Barva>Modrá, černá</Barva>
            <Materiál>Kůže, guma</Materiál>
            <Pohlaví>dámské</Pohlaví>
            <Velikost>38</Velikost>
            <CenaZaKus měna="CZK">1400</CenaZaKus>
            <Mnozstvi jednotky="kusy">15</Mnozstvi>
            <Značka>La Sportiva</Značka>
            <FotoURI>i6.png</FotoURI>
            <TXT>Velice měkká bota s velmi citlivou špičkou. Cobra dlouhou dobu určovala směr, jak má vypadat dobrá nazouvací lezka. Díky kvalitní kostrukci se lezečka nevyzouvá a poskytuje výbornou přilnavost i na špatných stupech. Cobra představuje lezečku s vysokým výkonem a přitom za dobrou cenu. Kopyto je středně široké a je potřeba vybírat o něco menší velikosti než u ostatních lezeček.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>1245789632DSACX</IdentifikačníČíslo>
            <Popis>Lezečky</Popis>
            <Barva>Hnědá, černá</Barva>
            <Materiál>Kůže</Materiál>
            <Pohlaví>pánské</Pohlaví>
            <Velikost>43</Velikost>
            <CenaZaKus měna="CZK">2500</CenaZaKus>
            <Mnozstvi jednotky="kusy">15</Mnozstvi>
            <Značka>La Sportiva</Značka>
            <FotoURI>i7.png</FotoURI>
            <TXT>Vyjímečně všetranná lezečka na šněrování. Pohodlná, vhodná pro začátečniky i pokročilé. Dobře se přizpůsobí každému typu chodidla.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>6548973109SADFG</IdentifikačníČíslo>
            <Popis>Lezečky</Popis>
            <Barva>Černá, modrá</Barva>
            <Materiál>Syntetická kůže</Materiál>
            <Pohlaví>univerzální</Pohlaví>
            <Velikost>45</Velikost>
            <CenaZaKus měna="CZK">1300</CenaZaKus>
            <Mnozstvi jednotky="kusy">2</Mnozstvi>
            <Značka>TRIOP</Značka>
            <FotoURI>i8.png</FotoURI>
            <TXT>Nový model lezečky od firmy Triop, který je určen pro všestranné lezení na umělých stěnách i skalách. Středně asymetrická a prohnutá konstrukce umožňuje celodenní lezení.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>3791328001SMBJK</IdentifikačníČíslo>
            <Popis>Kulich</Popis>
            <Barva>Černá</Barva>
            <Materiál>Vlna</Materiál>
            <Pohlaví>univerzální</Pohlaví>
            <Velikost>uviverzální</Velikost>
            <CenaZaKus měna="CZK">500</CenaZaKus>
            <Mnozstvi jednotky="kusy">20</Mnozstvi>
            <Značka>TRIOP</Značka>
            <FotoURI>i9.png</FotoURI>
            <TXT>Pletená vlněná čepice do největších mrazů. Díky průžnému provedění je adaptuje na kteroukoliv velikost a padne každému.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>4932650001SMCVK</IdentifikačníČíslo>
            <Popis>Rukavice</Popis>
            <Barva>černá</Barva>
            <Materiál>Vlna, Elastan</Materiál>
            <Pohlaví>dámské</Pohlaví>
            <Velikost>XS</Velikost>
            <CenaZaKus měna="CZK">1000</CenaZaKus>
            <Mnozstvi jednotky="kusy">14</Mnozstvi>
            <Značka>NorthFace</Značka>
            <FotoURI>i10.png</FotoURI>
            <TXT>260 Tech Glove Liners jsou oblíbené rukavice značky Icebreaker. Vylepšený design zahrnuje technologii pro ovládání dotykových obrazovek na palci a ukazováčku. Merino střední gramáže poskytuje skvělý tepelný komfort, skvěle sedí použitím materiálu LYCRA®. Rukavice lze nosit samostatně nebo jako hřejivá vložka do jiných rukavic.</TXT>
        </Položka>
        <Položka>
            <IdentifikačníČíslo>9951326102TRUJG</IdentifikačníČíslo>
            <Popis>Funkční prádlo</Popis>
            <Barva>Černá</Barva>
            <Materiál>Polyamid, Polypropylen</Materiál>
            <Pohlaví>pánské</Pohlaví>
            <Velikost>S</Velikost>
            <CenaZaKus měna="CZK">2600</CenaZaKus>
            <Mnozstvi jednotky="kusy">3</Mnozstvi>
            <Značka>UYN</Značka>
            <FotoURI>i11.png</FotoURI>
